[CHG] update config file

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,37 +1,40 @@
 version: 2.1
 
-# project_tag: DiT-UdaPeople
+# project_tag: dit-udapeople
 
 commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
-      # Add parameter here   
+      workflowID:
+        type: string    
     steps:
       - run:
           name: Destroy environments
           when: on_fail
           command: |
-            # Your code here
-            exit 1
+            aws s3 rm s3://dit-udapeople-<< parameters.workflowID >> --recursive
+            aws s3 rb s3://dit-udapeople-<< parameters.workflowID >> --force
+            aws cloudformation delete-stack --stack-name dit-udapeople-frontend-<< parameters.workflowID >>
+            aws cloudformation delete-stack --stack-name dit-udapeople-backend-<< parameters.workflowID >>
 
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
-      # Add parameter here     
+      workflowID:
+        type: string       
     steps:
       - run:
           name: Revert migrations
-          # Add when this will run
+          when: on_fail
           command: |
             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS = 1
+            SUCCESS=$(curl https://kvdb.io/${KVDB_BUCKET}/DB_MIGRATION_STATUS)
             if(( $SUCCESS==1 )); 
             then
-            #  cd ~/project/backend
-            #  npm install
-            #  Add revert code here. You can find this in the Getting Started section.
-              exit 1
+             cd ~/project/backend
+             npm install
+             npm run migrations:revert
             fi
             
 jobs:
@@ -45,8 +48,8 @@ jobs:
       - run:
           name: Build front-end
           command: |
-            # Your code here
-            exit 1
+            cd frontend
+            npm run build
       - save_cache:
           paths: [frontend/node_modules]
           key: frontend-build
@@ -61,8 +64,8 @@ jobs:
       - run:
           name: Back-end build
           command: |
-             # Your code here
-             exit 1
+             cd backend
+             npm run build
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
@@ -107,7 +110,7 @@ jobs:
           command: |
             cd frontend
             npm install
-            npm audit --audit-level=critical || true
+            npm audit --audit-level=critical
 
   scan-backend:
     docker:
@@ -121,7 +124,7 @@ jobs:
           command: |
             cd backend
             npm install
-            npm audit --audit-level=critical || true
+            npm audit --audit-level=critical
 
   deploy-infrastructure:
     docker:
@@ -137,24 +140,29 @@ jobs:
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/backend.yml \
-              --tags project=DiT-UdaPeople \
-              --stack-name "DiT-UdaPeople-BE-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --tags project=dit-udapeople \
+              --stack-name "dit-udapeople-BE-${CIRCLE_WORKFLOW_ID:0:7}" \
               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
-              exit 1
       - run:
           name: Ensure front-end infrastructure exist
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/frontend.yml \
-              # --tags project=DiT-UdaPeople \
-              # --stack-name "DiT-UdaPeople-FE-${CIRCLE_WORKFLOW_ID:0:7}" \
-              # --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
-              exit 1
+              --tags project=dit-udapeople \
+              --stack-name "dit-udapeople-FE-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
       - run:
           name: Add back-end ip to ansible inventory
           command: |
-            # Your code here
-            exit 1
+            BACKEND_IP=$(aws ec2 describe-instances \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --filters "Name=tag:project,Values=dit-udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --output text)
+            echo "${BACKEND_IP}"
+            curl https://kvdb.io/${KVDB_BUCKET}/BACKEND_IP  -d ${BACKEND_IP} 
+            echo ${BACKEND_IP} >> ./.circleci/ansible/inventory.txt
+            cat ./.circleci/ansible/inventory.txt
+
       - persist_to_workspace:
           root: ~/
           paths:
@@ -168,20 +176,19 @@ jobs:
       - image: python:3.7-alpine3.11
     steps:
       - checkout
-      add_ssh_keys:
-        fingerprints: ["e7:3d:8e:67:76:8c:5a:7d:e8:a8:f5:49:df:fc:f1:3c"]
+      - add_ssh_keys:
+          fingerprints: ["${SSH_FINGERPRINT}"]
       - attach_workspace:
           at: ~/
       - run:
           name: Install dependencies
           command: |
-            # Your code here
-            exit 1
+            apk add --update ansible
       - run:
           name: Configure server
           command: |
-            # Your code here
-            exit 1
+            cat inventory.txt
+            ansible-playbook -i ./.circleci/ansible/inventory.txt ./.circleci/ansible/configure-server.yml
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
           when: on_fail      
@@ -194,13 +201,21 @@ jobs:
       - run:
           name: Run migrations
           command: |
-            # Your code here
-            exit 1
+            cd ./backend
+            npm run migrations > migrations_log.txt
+            cat ./migrations_log.txt
       - run:
-          name: Send migration results to memstash
+          name: Send migration results to kvDB
           command: |
-            # Your code here
-            exit 1
+            if grep "has been executed successfully" ./backend/migrations_log.txt;
+            then
+              echo "Database migration has been executed successfully"
+              curl https://kvdb.io/${KVDB_BUCKET}/DB_MIGRATION_STATUS -d '1'
+            else
+              echo "Database migration has failed, verify DB setup!"
+              curl https://kvdb.io/${KVDB_BUCKET}/DB_MIGRATION_STATUS -d '0'
+              exit 1
+            fi
      - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
           when: on_fail    
@@ -213,17 +228,19 @@ jobs:
       - run:
           name: Install dependencies
           command: |
-            # your code here
+            yum install -y tar gzip curl
+            curl -sL https://rpm.nodesource.com/setup_10.x | bash -
+            yum install -y nodejs
       - run:
           name: Get backend url
           command: |
-            # your code here
+            BACKEND_IP=$(curl https://kvdb.io/${KVDB_BUCKET}/BACKEND_IP)
             export API_URL="http://${BACKEND_IP}:3030"
             echo "${API_URL}"
       - run:
           name: Deploy frontend objects
           command: |
-            # your code here
+            aws s3 cp ./frontend/dist "s3://dit-udapeople-${CIRCLE_WORKFLOW_ID:0:7}" --recursive
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
           when: on_fail     
@@ -234,76 +251,125 @@ jobs:
     steps:
       - checkout
      add_ssh_keys:
-        fingerprints: ["e7:3d:8e:67:76:8c:5a:7d:e8:a8:f5:49:df:fc:f1:3c"]
+        fingerprints: ["${SSH_FINGERPRINT}"]
       - attach_workspace:
           at: ~/
       - run:
           name: Install dependencies
           command: |
-            # your code here
+            apk add --no-cache curl
+            apk add --no-cache openssh-client
+            apk add --no-cache --upgrade bash
+            apk add --update ansible
+            pip install awscli
       - run:
           name: Deploy backend
           command: |
-            # your code here
+            tar czf backend.tar.gz backend/
+            export ANSIBLE_HOST_KEY_CHECKING=false
+            ansible-playbook -i ./.circleci/ansible/inventory.txt ./.circleci/ansible/deploy-backend.yml 
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
           when: on_fail
 
   smoke-test:
     docker:
-      # Lightweight Docker image 
+      - image: alpine:latest
     steps:
-      # Checkout code from git
+      - checkout
       - run:
           name: Install dependencies
           command: |
-            # your code here
+            apk --no-cache add curl
+            apk add --update npm
+            apk add --no-cache python3 py3-pip \
+              && pip3 install --upgrade pip \
+              && pip install awscli
       - run:
           name: Get backend url
           command: |
-            # your code here
+            BACKEND_IP=$(curl https://kvdb.io/${KVDB_BUCKET}/BACKEND_IP)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+            curl -s "${API_URL}/api/status" -v
       - run:
           name: Backend smoke test.
           command: |
-            # your code here
+            echo "${API_URL}"
+            curl -s "${API_URL}/api/status" -v
       - run:
           name: Frontend smoke test.
           command: |
-            # your code here
+            URL="http://dit-udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.us-east-1.amazonaws.com/index.html"
+            if curl -s ${URL}| grep "Moved";
+            then
+              echo "Frontend smoke test passed"
+            else
+              echo "Frontend smoke test failed"
+              exit 1
+            fi
+
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+          when: on_fail
+      - revert-migrations:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}  
+          when: on_fail
       # Here's where you will add some code to rollback on failure  
 
   cloudfront-update:
     docker:
       # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
     steps:
-      # Checkout code from git
+      - checkout
       - run:
           name: Install dependencies
           command: |
-            # your code here
+            yum install -y tar gzip curl
+            curl -sL https://rpm.nodesource.com/setup_10.x | bash -
+            yum install -y nodejs
       - run:
           name: Update cloudfront distribution
           command: |
-            # your code here
+            aws cloudformation deploy \
+              --template-file ./.circleci/files/cloudfront.yml \
+              --tags project=dit-udapeople \
+              --stack-name "dit-udapeople-cloudfront-production" \
+              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}"
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+          when: on_fail
+      - revert-migrations:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}  
+          when: on_fail
       # Here's where you will add some code to rollback on failure  
 
 cleanup:
     docker:
-      # Docker image here
+      - image: amazon/aws-cli
     steps:
-      # Checkout code from git
+      - checkout
       - run:
           name: Get old stack workflow id
           command: |
-            # your code here
-            export OldWorkflowID="the id here"
-            export STACKS=[] #put the list of stacks here
+            OLD_WORKFLOW_ID=$(aws cloudformation list-exports \
+              --query "Exports[?Name==\`WorkflowID\`].Value" \
+              --no-paginate --output text)
+            echo "$OLD_WORKFLOW_ID"
+            export OldWorkflowID="$OLD_WORKFLOW_ID"
+            export STACKS=${CIRCLE_WORKFLOW_ID:0:7}
+            echo "${OldWorkflowID}"
       - run:
           name: Remove old stacks and files
           command: |
-            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+            if [[ "${STACKS}" != "${OldWorkflowID}" ]]
             then
-              # your code here
+              aws s3 rm "s3://dit-udapeople-${OldWorkflowID}" --recursive
+              aws cloudformation delete-stack --stack-name "dit-udapeople-frontend-${OldWorkflowID}"
+              aws cloudformation delete-stack --stack-name "dit-udapeople-backend-${OldWorkflowID}"
+            else
+              echo "No old stacks to remove"
             fi
             
 
